# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Boilermake5' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Boilermake5
  pod 'Realm'
  pod 'RealmSwift'
  pod 'FontAwesomeKit'
  pod 'Kingfisher'
  pod 'TesseractOCRiOS', '4.0.0'

  target 'Boilermake5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Boilermake5UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
